#!/bin/bash
# ============================================================================
# Blue-Green Deployment Orchestrator
# ============================================================================
# This script manages zero-downtime deployments by switching between
# blue and green environments.
#
# Usage:
#   ./deploy.sh <command> [options]
#
# Commands:
#   deploy      Deploy new version to inactive environment
#   switch      Switch traffic to specified environment
#   rollback    Rollback to previous environment
#   status      Show current deployment status
#   health      Run health checks on both environments
# ============================================================================

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}]")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEPLOYMENT_DIR="$PROJECT_ROOT/deployment"
NGINX_CONF_DIR="/etc/nginx/conf.d"
ACTIVE_ENV_FILE="$NGINX_CONF_DIR/active-backend.conf"

# Docker Compose files
DOCKER_COMPOSE_BLUE="$DEPLOYMENT_DIR/docker-compose.blue.yml"
DOCKER_COMPOSE_GREEN="$DEPLOYMENT_DIR/docker-compose.green.yml"

# Health check endpoints
HEALTH_ENDPOINT="/api/health"
HEALTH_CHECK_TIMEOUT=30
HEALTH_CHECK_RETRIES=5
HEALTH_CHECK_INTERVAL=2

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get current active environment
get_active_env() {
    if [ -f "$ACTIVE_ENV_FILE" ]; then
        grep -o 'upstream_backend_[a-z]*' "$ACTIVE_ENV_FILE" | cut -d'_' -f3
    else
        echo "blue"  # Default to blue
    fi
}

# Get inactive environment
get_inactive_env() {
    local active
    active=$(get_active_env)
    if [ "$active" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# ============================================================================
# Health Check Functions
# ============================================================================

check_health() {
    local env=$1
    local port=$2
    local retries=${3:-$HEALTH_CHECK_RETRIES}
    
    log_info "Running health checks on $env environment (port $port)..."
    
    for i in $(seq 1 $retries); do
        if curl -sf "http://localhost:$port$HEALTH_ENDPOINT" > /dev/null 2>&1; then
            log_success "Health check passed for $env (attempt $i/$retries)"
            return 0
        fi
        log_warning "Health check attempt $i/$retries failed, retrying in ${HEALTH_CHECK_INTERVAL}s..."
        sleep $HEALTH_CHECK_INTERVAL
    done
    
    log_error "Health check failed for $env after $retries attempts"
    return 1
}

check_all_services() {
    local env=$1
    local backend_port=$2
    local frontend_port=$3
    local techhub_port=$4
    
    log_info "Checking all services for $env environment..."
    
    # Check backend
    if ! check_health "$env-backend" "$backend_port" 3; then
        return 1
    fi
    
    # Check frontend
    if ! curl -sf "http://localhost:$frontend_port" > /dev/null 2>&1; then
        log_error "Frontend health check failed for $env"
        return 1
    fi
    
    # Check tech hub
    if ! curl -sf "http://localhost:$techhub_port" > /dev/null 2>&1; then
        log_error "Tech Hub health check failed for $env"
        return 1
    fi
    
    log_success "All services healthy for $env environment"
    return 0
}

# ============================================================================
# Deployment Functions
# ============================================================================

deploy_environment() {
    local env=$1
    local version=$2
    
    log_info "Deploying version $version to $env environment..."
    
    # Build and start services
    if [ "$env" = "blue" ]; then
        docker-compose -f "$DOCKER_COMPOSE_BLUE" build
        docker-compose -f "$DOCKER_COMPOSE_BLUE" up -d
    else
        docker-compose -f "$DOCKER_COMPOSE_GREEN" build
        docker-compose -f "$DOCKER_COMPOSE_GREEN" up -d
    fi
    
    # Wait for services to start
    sleep 10
    
    # Run health checks
    if [ "$env" = "blue" ]; then
        check_all_services "$env" 5001 3000 4321
    else
        check_all_services "$env" 5002 3001 4322
    fi
    
    log_success "Deployment to $env environment completed"
}

switch_traffic() {
    local target_env=$1
    
    log_info "Switching traffic to $target_env environment..."
    
    # Create active backend configuration
    cat > "$ACTIVE_ENV_FILE" << EOF
# Active backend environment - auto-generated by deploy.sh
# Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Target environment: $target_env

set \$active_backend "backend_$target_env";
set \$active_frontend "frontend_$target_env";
set \$active_techhub "techhub_$target_env";
EOF
    
    # Reload nginx
    if nginx -t 2>/dev/null; then
        nginx -s reload
        log_success "Nginx reloaded, traffic now routing to $target_env"
    else
        log_error "Nginx configuration test failed"
        return 1
    fi
    
    # Verify traffic switch
    sleep 2
    if check_health "switched" 80 3; then
        log_success "Traffic switch verified"
        return 0
    else
        log_error "Traffic switch verification failed"
        return 1
    fi
}

rollback() {
    local current_env
    local target_env
    
    current_env=$(get_active_env)
    target_env=$(get_inactive_env)
    
    log_warning "Rolling back from $current_env to $target_env..."
    
    # Switch traffic
    if switch_traffic "$target_env"; then
        log_success "Rollback completed successfully"
        log_info "Previous environment ($current_env) is now standby"
    else
        log_error "Rollback failed"
        return 1
    fi
}

show_status() {
    local active_env
    active_env=$(get_active_env)
    local inactive_env
    inactive_env=$(get_inactive_env)
    
    echo ""
    echo "============================================================================"
    echo "                    Blue-Green Deployment Status"
    echo "============================================================================"
    echo ""
    echo "  Active Environment:   $active_env"
    echo "  Standby Environment:  $inactive_env"
    echo ""
    echo "  Services:"
    
    if [ "$active_env" = "blue" ]; then
        echo "    Backend:   localhost:5001 (active) | localhost:5002 (standby)"
        echo "    Frontend:  localhost:3000 (active) | localhost:3001 (standby)"
        echo "    Tech Hub:  localhost:4321 (active) | localhost:4322 (standby)"
    else
        echo "    Backend:   localhost:5001 (standby) | localhost:5002 (active)"
        echo "    Frontend:  localhost:3000 (standby) | localhost:3001 (active)"
        echo "    Tech Hub:  localhost:4321 (standby) | localhost:4322 (active)"
    fi
    
    echo ""
    echo "  Docker Containers:"
    docker-compose -f "$DOCKER_COMPOSE_BLUE" ps 2>/dev/null || echo "    Blue: Not running"
    docker-compose -f "$DOCKER_COMPOSE_GREEN" ps 2>/dev/null || echo "    Green: Not running"
    echo ""
    echo "============================================================================"
    echo ""
}

# ============================================================================
# Main Command Handler
# ============================================================================

case "${1:-help}" in
    deploy)
        if [ -z "${2:-}" ]; then
            log_error "Usage: $0 deploy <version>"
            exit 1
        fi
        
        VERSION=$2
        INACTIVE_ENV=$(get_inactive_env)
        
        log_info "Starting deployment of version $VERSION to $INACTIVE_ENV environment..."
        
        # Deploy to inactive environment
        deploy_environment "$INACTIVE_ENV" "$VERSION"
        
        # Switch traffic
        switch_traffic "$INACTIVE_ENV"
        
        log_success "Deployment of version $VERSION completed successfully!"
        log_info "Previous environment is now on standby for rollback"
        ;;
    
    switch)
        if [ -z "${2:-}" ]; then
            log_error "Usage: $0 switch <blue|green>"
            exit 1
        fi
        
        TARGET_ENV=$2
        
        if [ "$TARGET_ENV" != "blue" ] && [ "$TARGET_ENV" != "green" ]; then
            log_error "Environment must be 'blue' or 'green'"
            exit 1
        fi
        
        switch_traffic "$TARGET_ENV"
        ;;
    
    rollback)
        rollback
        ;;
    
    status)
        show_status
        ;;
    
    health)
        ACTIVE_ENV=$(get_active_env)
        INACTIVE_ENV=$(get_inactive_env)
        
        echo ""
        log_info "Running health checks..."
        echo ""
        
        if [ "$ACTIVE_ENV" = "blue" ]; then
            check_all_services "blue" 5001 3000 4321
            check_all_services "green" 5002 3001 4322
        else
            check_all_services "green" 5002 3001 4322
            check_all_services "blue" 5001 3000 4321
        fi
        ;;
    
    help|*)
        echo ""
        echo "============================================================================"
        echo "                    Blue-Green Deployment Orchestrator"
        echo "============================================================================"
        echo ""
        echo "Usage: $0 <command> [options]"
        echo ""
        echo "Commands:"
        echo "  deploy <version>     Deploy new version to inactive environment"
        echo "  switch <env>         Switch traffic to specified environment (blue|green)"
        echo "  rollback             Rollback to previous environment"
        echo "  status               Show current deployment status"
        echo "  health               Run health checks on both environments"
        echo "  help                 Show this help message"
        echo ""
        echo "Examples:"
        echo "  $0 deploy v1.2.3     Deploy version 1.2.3"
        echo "  $0 switch green      Switch traffic to green environment"
        echo "  $0 rollback          Rollback to previous environment"
        echo ""
        echo "============================================================================"
        echo ""
        ;;
esac
